base_url = "https://ibra.github.io"
theme = "terminimal"

title = "ibra after dark"

default_language = "en"
compile_sass = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
author = "Ibrahim"

taxonomies = [{ name = "categories" }]

accent_color = "green"
background_color = "dark"

logo_text = "ibra after dark"
copyright_html = "©&nbsp;2022&nbsp; <a href=\"https://github.com/ibra\"><b>Ibrahim Hisham</b></a>|&nbsp;<a href=\"https://www.getzola.org/\">Zola</a>&nbsp;is&nbsp;epic 🧡"
post_view_navigation_prompt = "More from me"

favicon = "/favicon.png"
favicon_mimetype = "image/png"

menu_items = [
    # { name = "<- return to main", url = "https://google.com" },
    { name = "home", url = "$BASE_URL" },
    { name = "archive", url = "$BASE_URL/archive" },
    { name = "github", url = "https://github.com/ibra", newtab = true },
]
